package com.family.grabserver.entity;

public class CinemaBaidu {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.baidu_city_name
   *
   * @mbggenerated
   */
  private String baiduCityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.baidu_area
   *
   * @mbggenerated
   */
  private String baiduArea;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.city_name
   *
   * @mbggenerated
   */
  private String cityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.area_id
   *
   * @mbggenerated
   */
  private Integer areaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.area_name
   *
   * @mbggenerated
   */
  private String areaName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column cinema_baidu.address
   *
   * @mbggenerated
   */
  private String address;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.id
   *
   * @return the value of cinema_baidu.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_baidu.id
     *
     * @param id the value for cinema_baidu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.baidu_city_name
   *
   * @return the value of cinema_baidu.baidu_city_name
   *
   * @mbggenerated
   */
  public String getBaiduCityName() {
    return baiduCityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.baidu_city_name
   *
   * @param baiduCityName the value for cinema_baidu.baidu_city_name
   *
   * @mbggenerated
   */
  public void setBaiduCityName(String baiduCityName) {
    this.baiduCityName = baiduCityName == null ? null : baiduCityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.baidu_area
   *
   * @return the value of cinema_baidu.baidu_area
   *
   * @mbggenerated
   */
  public String getBaiduArea() {
    return baiduArea;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.baidu_area
   *
   * @param baiduArea the value for cinema_baidu.baidu_area
   *
   * @mbggenerated
   */
  public void setBaiduArea(String baiduArea) {
    this.baiduArea = baiduArea == null ? null : baiduArea.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.city_id
   *
   * @return the value of cinema_baidu.city_id
   *
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.city_id
   *
   * @param cityId the value for cinema_baidu.city_id
   *
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.city_name
   *
   * @return the value of cinema_baidu.city_name
   *
   * @mbggenerated
   */
  public String getCityName() {
    return cityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.city_name
   *
   * @param cityName the value for cinema_baidu.city_name
   *
   * @mbggenerated
   */
  public void setCityName(String cityName) {
    this.cityName = cityName == null ? null : cityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.area_id
   *
   * @return the value of cinema_baidu.area_id
   *
   * @mbggenerated
   */
  public Integer getAreaId() {
    return areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.area_id
   *
   * @param areaId the value for cinema_baidu.area_id
   *
   * @mbggenerated
   */
  public void setAreaId(Integer areaId) {
    this.areaId = areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.area_name
   *
   * @return the value of cinema_baidu.area_name
   *
   * @mbggenerated
   */
  public String getAreaName() {
    return areaName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.area_name
   *
   * @param areaName the value for cinema_baidu.area_name
   *
   * @mbggenerated
   */
  public void setAreaName(String areaName) {
    this.areaName = areaName == null ? null : areaName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.name
   *
   * @return the value of cinema_baidu.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.name
   *
   * @param name the value for cinema_baidu.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column cinema_baidu.address
   *
   * @return the value of cinema_baidu.address
   *
   * @mbggenerated
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column cinema_baidu.address
   *
   * @param address the value for cinema_baidu.address
   *
   * @mbggenerated
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }
}
