package com.family.webserver.entity;

public class Comment {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.id
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.movie_id
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private Integer movieId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.title
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private String title;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.nick_name
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private String nickName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.rating
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private Float rating;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.source
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private String source;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column comment.content
   *
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  private String content;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.id
   *
   * @return the value of comment.id
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.id
   *
   * @param id the value for comment.id
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.movie_id
   *
   * @return the value of comment.movie_id
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.movie_id
   *
   * @param movieId the value for comment.movie_id
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.title
   *
   * @return the value of comment.title
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public String getTitle() {
    return title;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.title
   *
   * @param title the value for comment.title
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.nick_name
   *
   * @return the value of comment.nick_name
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.nick_name
   *
   * @param nickName the value for comment.nick_name
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setNickName(String nickName) {
    this.nickName = nickName == null ? null : nickName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.rating
   *
   * @return the value of comment.rating
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public Float getRating() {
    return rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.rating
   *
   * @param rating the value for comment.rating
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setRating(Float rating) {
    this.rating = rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.source
   *
   * @return the value of comment.source
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public String getSource() {
    return source;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.source
   *
   * @param source the value for comment.source
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setSource(String source) {
    this.source = source == null ? null : source.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column comment.content
   *
   * @return the value of comment.content
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column comment.content
   *
   * @param content the value for comment.content
   * @mbggenerated Tue Feb 02 16:34:46 CST 2016
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }
}
