package com.family.webserver.entity;

public class Image {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column image.id
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column image.movie_id
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private Integer movieId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column image.image_url
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private String imageUrl;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column image.id
   *
   * @return the value of image.id
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbggenerated Fri Feb 05 11:16:29 CST 2016
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column image.movie_id
   *
   * @return the value of image.movie_id
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column image.movie_id
   *
   * @param movieId the value for image.movie_id
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column image.image_url
   *
   * @return the value of image.image_url
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public String getImageUrl() {
    return imageUrl;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column image.image_url
   *
   * @param imageUrl the value for image.image_url
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl == null ? null : imageUrl.trim();
  }
}
