package com.family.webserver.entity;

public class Source {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column source.id
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column source.name
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column source.content
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  private String content;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column source.id
   *
   * @return the value of source.id
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.id
     *
     * @param id the value for source.id
     *
     * @mbggenerated Fri Feb 05 11:16:29 CST 2016
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column source.name
   *
   * @return the value of source.name
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column source.name
   *
   * @param name the value for source.name
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column source.content
   *
   * @return the value of source.content
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column source.content
   *
   * @param content the value for source.content
   *
   * @mbggenerated Fri Feb 05 11:16:29 CST 2016
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }
}
