package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaBaidu;

import java.util.List;

public interface CinemaBaiduMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table cinema_baidu
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table cinema_baidu
   *
   * @mbggenerated
   */
  int insert(CinemaBaidu record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table cinema_baidu
   *
   * @mbggenerated
   */
  CinemaBaidu selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table cinema_baidu
   *
   * @mbggenerated
   */
  List<CinemaBaidu> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table cinema_baidu
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CinemaBaidu record);
}
