package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaTaobao;

import java.util.List;

public interface CinemaTaobaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_taobao
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_taobao
     *
     * @mbggenerated
     */
    int insert(CinemaTaobao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_taobao
     *
     * @mbggenerated
     */
    CinemaTaobao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_taobao
     *
     * @mbggenerated
     */
    List<CinemaTaobao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_taobao
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemaTaobao record);
}
