package com.family.grabserver.mapper;

import com.family.grabserver.entity.CityBaidu;

import java.util.List;

public interface CityBaiduMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_baidu
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_baidu
   *
   * @mbggenerated
   */
  int insert(CityBaidu record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_baidu
   *
   * @mbggenerated
   */
  CityBaidu selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_baidu
   *
   * @mbggenerated
   */
  List<CityBaidu> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_baidu
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CityBaidu record);
}
