package com.family.grabserver.mapper;

import com.family.grabserver.entity.MovieshowingBaidu;

import java.util.List;

public interface MovieshowingBaiduMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_baidu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_baidu
     *
     * @mbggenerated
     */
    int insert(MovieshowingBaidu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_baidu
     *
     * @mbggenerated
     */
    MovieshowingBaidu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_baidu
     *
     * @mbggenerated
     */
    List<MovieshowingBaidu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_baidu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieshowingBaidu record);
}
