package com.family.grabserver.mapper.bim_base;

import com.family.grabserver.entity.bim_base.City;

import java.util.List;

public interface CityMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..city
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..city
   *
   * @mbggenerated
   */
  int insert(City record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..city
   *
   * @mbggenerated
   */
  City selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..city
   *
   * @mbggenerated
   */
  List<City> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..city
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(City record);
}
