package com.family.grabserver.mapper.bim_base;

import com.family.grabserver.entity.bim_base.Image;

import java.util.List;

public interface ImageMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..image
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..image
   *
   * @mbggenerated
   */
  int insert(Image record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..image
   *
   * @mbggenerated
   */
  Image selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..image
   *
   * @mbggenerated
   */
  List<Image> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..image
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Image record);
}
