package com.family.grabserver.mapper.bim_base;

import com.family.grabserver.entity.bim_base.Movieshowing;

import java.util.List;

public interface MovieshowingMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..movieshowing
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..movieshowing
   *
   * @mbggenerated
   */
  int insert(Movieshowing record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..movieshowing
   *
   * @mbggenerated
   */
  Movieshowing selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..movieshowing
   *
   * @mbggenerated
   */
  List<Movieshowing> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..movieshowing
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Movieshowing record);
}
