package com.family.grabserver.mapper.bim_base;

import com.family.grabserver.entity.bim_base.Screening;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScreeningMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall, @Param("sourceId") Integer sourceId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int insert(Screening record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  Screening selectByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall, @Param("sourceId") Integer sourceId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  List<Screening> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Screening record);
}
