package com.family.grabserver.mapper.bim_base;

import com.family.grabserver.entity.bim_base.Screening;

import java.util.List;

public interface ScreeningMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int insert(Screening record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  Screening selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  List<Screening> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_base..screening
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Screening record);
}
