package com.family.grabserver.entity.bim_grab;

public class CinemaMaoyan {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.maoyan_city_name
   *
   * @mbggenerated
   */
  private Integer maoyanCityId;


  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.maoyan_city_name
   *
   * @mbggenerated
   */
  private String maoyanCityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.maoyan_area
   *
   * @mbggenerated
   */
  private String maoyanArea;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.city_name
   *
   * @mbggenerated
   */
  private String cityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.area_id
   *
   * @mbggenerated
   */
  private Integer areaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.area_name
   *
   * @mbggenerated
   */
  private String areaName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_maoyan.address
   *
   * @mbggenerated
   */
  private String address;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.id
   *
   * @return the value of bim_grab..cinema_maoyan.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.id
   *
   * @param id the value for bim_grab..cinema_maoyan.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.maoyan_city_id
   *
   * @return the value of bim_grab..cinema_maoyan.maoyan_city_id
   * @mbggenerated
   */
  public Integer getMaoyanCityId() {
    return maoyanCityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.maoyan_city_id
   *
   * @param maoyanCityId the value for bim_grab..cinema_maoyan.maoyan_city_id
   * @mbggenerated
   */
  public void setMaoyanCityId(Integer maoyanCityId) {
    this.maoyanCityId = maoyanCityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.maoyan_city_name
   *
   * @return the value of bim_grab..cinema_maoyan.maoyan_city_name
   * @mbggenerated
   */
  public String getMaoyanCityName() {
    return maoyanCityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.maoyan_city_name
   *
   * @param maoyanCityName the value for bim_grab..cinema_maoyan.maoyan_city_name
   * @mbggenerated
   */
  public void setMaoyanCityName(String maoyanCityName) {
    this.maoyanCityName = maoyanCityName == null ? null : maoyanCityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.maoyan_area
   *
   * @return the value of bim_grab..cinema_maoyan.maoyan_area
   * @mbggenerated
   */
  public String getMaoyanArea() {
    return maoyanArea;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.maoyan_area
   *
   * @param maoyanArea the value for bim_grab..cinema_maoyan.maoyan_area
   * @mbggenerated
   */
  public void setMaoyanArea(String maoyanArea) {
    this.maoyanArea = maoyanArea == null ? null : maoyanArea.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.city_id
   *
   * @return the value of bim_grab..cinema_maoyan.city_id
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.city_id
   *
   * @param cityId the value for bim_grab..cinema_maoyan.city_id
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.city_name
   *
   * @return the value of bim_grab..cinema_maoyan.city_name
   * @mbggenerated
   */
  public String getCityName() {
    return cityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.city_name
   *
   * @param cityName the value for bim_grab..cinema_maoyan.city_name
   * @mbggenerated
   */
  public void setCityName(String cityName) {
    this.cityName = cityName == null ? null : cityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.area_id
   *
   * @return the value of bim_grab..cinema_maoyan.area_id
   * @mbggenerated
   */
  public Integer getAreaId() {
    return areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.area_id
   *
   * @param areaId the value for bim_grab..cinema_maoyan.area_id
   * @mbggenerated
   */
  public void setAreaId(Integer areaId) {
    this.areaId = areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.area_name
   *
   * @return the value of bim_grab..cinema_maoyan.area_name
   * @mbggenerated
   */
  public String getAreaName() {
    return areaName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.area_name
   *
   * @param areaName the value for bim_grab..cinema_maoyan.area_name
   * @mbggenerated
   */
  public void setAreaName(String areaName) {
    this.areaName = areaName == null ? null : areaName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.name
   *
   * @return the value of bim_grab..cinema_maoyan.name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.name
   *
   * @param name the value for bim_grab..cinema_maoyan.name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_maoyan.address
   *
   * @return the value of bim_grab..cinema_maoyan.address
   * @mbggenerated
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_maoyan.address
   *
   * @param address the value for bim_grab..cinema_maoyan.address
   * @mbggenerated
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }
}
