package com.family.grabserver.entity.bim_grab;

public class CinemaBaidu {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_baidu.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_baidu.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_baidu.area
   *
   * @mbggenerated
   */
  private String area;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_baidu.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_baidu.address
   *
   * @mbggenerated
   */
  private String address;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_baidu.id
   *
   * @return the value of bim_grab..cinema_baidu.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_baidu.id
   *
   * @param id the value for bim_grab..cinema_baidu.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_baidu.city_id
   *
   * @return the value of bim_grab..cinema_baidu.city_id
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_baidu.city_id
   *
   * @param cityId the value for bim_grab..cinema_baidu.city_id
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_baidu.area
   *
   * @return the value of bim_grab..cinema_baidu.area
   * @mbggenerated
   */
  public String getArea() {
    return area;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_baidu.area
   *
   * @param area the value for bim_grab..cinema_baidu.area
   * @mbggenerated
   */
  public void setArea(String area) {
    this.area = area == null ? null : area.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_baidu.name
   *
   * @return the value of bim_grab..cinema_baidu.name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_baidu.name
   *
   * @param name the value for bim_grab..cinema_baidu.name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_baidu.address
   *
   * @return the value of bim_grab..cinema_baidu.address
   * @mbggenerated
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_baidu.address
   *
   * @param address the value for bim_grab..cinema_baidu.address
   * @mbggenerated
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }
}
