package com.family.grabserver.entity.bim_grab;

public class CinemaWeixin {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.weixin_city_id
   *
   * @mbggenerated
   */
  private Integer weixinCityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.weixin_city_name
   *
   * @mbggenerated
   */
  private String weixinCityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.weixin_area
   *
   * @mbggenerated
   */
  private String weixinArea;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.city_name
   *
   * @mbggenerated
   */
  private String cityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.area_id
   *
   * @mbggenerated
   */
  private Integer areaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.area_name
   *
   * @mbggenerated
   */
  private String areaName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.address
   *
   * @mbggenerated
   */
  private String address;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.latitude
   *
   * @mbggenerated
   */
  private String latitude;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.longitude
   *
   * @mbggenerated
   */
  private String longitude;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_weixin.tel
   *
   * @mbggenerated
   */
  private String tel;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.id
   *
   * @return the value of bim_grab..cinema_weixin.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_grab..cinema_weixin.id
     *
     * @param id the value for bim_grab..cinema_weixin.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.weixin_city_id
   *
   * @return the value of bim_grab..cinema_weixin.weixin_city_id
   *
   * @mbggenerated
   */
  public Integer getWeixinCityId() {
    return weixinCityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.weixin_city_id
   *
   * @param weixinCityId the value for bim_grab..cinema_weixin.weixin_city_id
   *
   * @mbggenerated
   */
  public void setWeixinCityId(Integer weixinCityId) {
    this.weixinCityId = weixinCityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.weixin_city_name
   *
   * @return the value of bim_grab..cinema_weixin.weixin_city_name
   *
   * @mbggenerated
   */
  public String getWeixinCityName() {
    return weixinCityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.weixin_city_name
   *
   * @param weixinCityName the value for bim_grab..cinema_weixin.weixin_city_name
   *
   * @mbggenerated
   */
  public void setWeixinCityName(String weixinCityName) {
    this.weixinCityName = weixinCityName == null ? null : weixinCityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.weixin_area
   *
   * @return the value of bim_grab..cinema_weixin.weixin_area
   *
   * @mbggenerated
   */
  public String getWeixinArea() {
    return weixinArea;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.weixin_area
   *
   * @param weixinArea the value for bim_grab..cinema_weixin.weixin_area
   *
   * @mbggenerated
   */
  public void setWeixinArea(String weixinArea) {
    this.weixinArea = weixinArea == null ? null : weixinArea.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.city_id
   *
   * @return the value of bim_grab..cinema_weixin.city_id
   *
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.city_id
   *
   * @param cityId the value for bim_grab..cinema_weixin.city_id
   *
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.city_name
   *
   * @return the value of bim_grab..cinema_weixin.city_name
   *
   * @mbggenerated
   */
  public String getCityName() {
    return cityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.city_name
   *
   * @param cityName the value for bim_grab..cinema_weixin.city_name
   *
   * @mbggenerated
   */
  public void setCityName(String cityName) {
    this.cityName = cityName == null ? null : cityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.area_id
   *
   * @return the value of bim_grab..cinema_weixin.area_id
   *
   * @mbggenerated
   */
  public Integer getAreaId() {
    return areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.area_id
   *
   * @param areaId the value for bim_grab..cinema_weixin.area_id
   *
   * @mbggenerated
   */
  public void setAreaId(Integer areaId) {
    this.areaId = areaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.area_name
   *
   * @return the value of bim_grab..cinema_weixin.area_name
   *
   * @mbggenerated
   */
  public String getAreaName() {
    return areaName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.area_name
   *
   * @param areaName the value for bim_grab..cinema_weixin.area_name
   *
   * @mbggenerated
   */
  public void setAreaName(String areaName) {
    this.areaName = areaName == null ? null : areaName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.name
   *
   * @return the value of bim_grab..cinema_weixin.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.name
   *
   * @param name the value for bim_grab..cinema_weixin.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.address
   *
   * @return the value of bim_grab..cinema_weixin.address
   *
   * @mbggenerated
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.address
   *
   * @param address the value for bim_grab..cinema_weixin.address
   *
   * @mbggenerated
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.latitude
   *
   * @return the value of bim_grab..cinema_weixin.latitude
   *
   * @mbggenerated
   */
  public String getLatitude() {
    return latitude;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.latitude
   *
   * @param latitude the value for bim_grab..cinema_weixin.latitude
   *
   * @mbggenerated
   */
  public void setLatitude(String latitude) {
    this.latitude = latitude == null ? null : latitude.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.longitude
   *
   * @return the value of bim_grab..cinema_weixin.longitude
   *
   * @mbggenerated
   */
  public String getLongitude() {
    return longitude;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.longitude
   *
   * @param longitude the value for bim_grab..cinema_weixin.longitude
   *
   * @mbggenerated
   */
  public void setLongitude(String longitude) {
    this.longitude = longitude == null ? null : longitude.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_weixin.tel
   *
   * @return the value of bim_grab..cinema_weixin.tel
   * @mbggenerated
   */
  public String getTel() {
    return tel;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_weixin.tel
   *
   * @param tel the value for bim_grab..cinema_weixin.tel
   * @mbggenerated
   */
  public void setTel(String tel) {
    this.tel = tel == null ? null : tel.trim();
  }
}
