package com.family.grabserver.entity.bim_grab;

public class CinemamovieMaoyan {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinemamovie_maoyan.cinema_id
   *
   * @mbggenerated
   */
  private Integer cinemaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinemamovie_maoyan.movie_id
   *
   * @mbggenerated
   */
  private Integer movieId;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinemamovie_maoyan.cinema_id
   *
   * @return the value of bim_grab..cinemamovie_maoyan.cinema_id
   * @mbggenerated
   */
  public Integer getCinemaId() {
    return cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinemamovie_maoyan.cinema_id
   *
   * @param cinemaId the value for bim_grab..cinemamovie_maoyan.cinema_id
   * @mbggenerated
   */
  public void setCinemaId(Integer cinemaId) {
    this.cinemaId = cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinemamovie_maoyan.movie_id
   *
   * @return the value of bim_grab..cinemamovie_maoyan.movie_id
   * @mbggenerated
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinemamovie_maoyan.movie_id
   *
   * @param movieId the value for bim_grab..cinemamovie_maoyan.movie_id
   * @mbggenerated
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

}
