package com.family.grabserver.entity.bim_grab;

public class CinemaTaobao {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.area
   *
   * @mbggenerated
   */
  private String area;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.address
   *
   * @mbggenerated
   */
  private String address;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.latitude
   *
   * @mbggenerated
   */
  private String latitude;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.longitude
   *
   * @mbggenerated
   */
  private String longitude;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.preferential
   *
   * @mbggenerated
   */
  private Boolean preferential;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.tel
   *
   * @mbggenerated
   */
  private String tel;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cinema_taobao.json_md5
   *
   * @mbggenerated
   */
  private String jsonMd5;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.id
   *
   * @return the value of bim_grab..cinema_taobao.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_grab..cinema_taobao.id
     *
     * @param id the value for bim_grab..cinema_taobao.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.city_id
   *
   * @return the value of bim_grab..cinema_taobao.city_id
   *
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.city_id
   *
   * @param cityId the value for bim_grab..cinema_taobao.city_id
   *
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.name
   *
   * @return the value of bim_grab..cinema_taobao.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.name
   *
   * @param name the value for bim_grab..cinema_taobao.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.area
   *
   * @return the value of bim_grab..cinema_taobao.area
   *
   * @mbggenerated
   */
  public String getArea() {
    return area;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.area
   *
   * @param area the value for bim_grab..cinema_taobao.area
   *
   * @mbggenerated
   */
  public void setArea(String area) {
    this.area = area == null ? null : area.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.address
   *
   * @return the value of bim_grab..cinema_taobao.address
   *
   * @mbggenerated
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.address
   *
   * @param address the value for bim_grab..cinema_taobao.address
   *
   * @mbggenerated
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.latitude
   *
   * @return the value of bim_grab..cinema_taobao.latitude
   *
   * @mbggenerated
   */
  public String getLatitude() {
    return latitude;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.latitude
   *
   * @param latitude the value for bim_grab..cinema_taobao.latitude
   *
   * @mbggenerated
   */
  public void setLatitude(String latitude) {
    this.latitude = latitude == null ? null : latitude.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.longitude
   *
   * @return the value of bim_grab..cinema_taobao.longitude
   *
   * @mbggenerated
   */
  public String getLongitude() {
    return longitude;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.longitude
   *
   * @param longitude the value for bim_grab..cinema_taobao.longitude
   *
   * @mbggenerated
   */
  public void setLongitude(String longitude) {
    this.longitude = longitude == null ? null : longitude.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.preferential
   *
   * @return the value of bim_grab..cinema_taobao.preferential
   *
   * @mbggenerated
   */
  public Boolean getPreferential() {
    return preferential;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.preferential
   *
   * @param preferential the value for bim_grab..cinema_taobao.preferential
   *
   * @mbggenerated
   */
  public void setPreferential(Boolean preferential) {
    this.preferential = preferential;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.tel
   *
   * @return the value of bim_grab..cinema_taobao.tel
   *
   * @mbggenerated
   */
  public String getTel() {
    return tel;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.tel
   *
   * @param tel the value for bim_grab..cinema_taobao.tel
   *
   * @mbggenerated
   */
  public void setTel(String tel) {
    this.tel = tel == null ? null : tel.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cinema_taobao.json_md5
   *
   * @return the value of bim_grab..cinema_taobao.json_md5
   *
   * @mbggenerated
   */
  public String getJsonMd5() {
    return jsonMd5;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cinema_taobao.json_md5
   *
   * @param jsonMd5 the value for bim_grab..cinema_taobao.json_md5
   *
   * @mbggenerated
   */
  public void setJsonMd5(String jsonMd5) {
    this.jsonMd5 = jsonMd5 == null ? null : jsonMd5.trim();
  }
}
