package com.family.grabserver.entity.bim_grab;

public class CityWithArea {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..city_with_area.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..city_with_area.city_name
   *
   * @mbggenerated
   */
  private String cityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..city_with_area.area_name
   *
   * @mbggenerated
   */
  private String areaName;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..city_with_area.id
   *
   * @return the value of bim_grab..city_with_area.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..city_with_area.id
   *
   * @param id the value for bim_grab..city_with_area.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..city_with_area.city_name
   *
   * @return the value of bim_grab..city_with_area.city_name
   * @mbggenerated
   */
  public String getCityName() {
    return cityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..city_with_area.city_name
   *
   * @param cityName the value for bim_grab..city_with_area.city_name
   * @mbggenerated
   */
  public void setCityName(String cityName) {
    this.cityName = cityName == null ? null : cityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..city_with_area.area_name
   *
   * @return the value of bim_grab..city_with_area.area_name
   * @mbggenerated
   */
  public String getAreaName() {
    return areaName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..city_with_area.area_name
   *
   * @param areaName the value for bim_grab..city_with_area.area_name
   * @mbggenerated
   */
  public void setAreaName(String areaName) {
    this.areaName = areaName == null ? null : areaName.trim();
  }
}
