package com.family.grabserver.entity.bim_grab;

public class CityareaBaidu {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cityarea_baidu.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cityarea_baidu.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cityarea_baidu.city_name
   *
   * @mbggenerated
   */
  private String cityName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..cityarea_baidu.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cityarea_baidu.id
   *
   * @return the value of bim_grab..cityarea_baidu.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_grab..cityarea_baidu.id
     *
     * @param id the value for bim_grab..cityarea_baidu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cityarea_baidu.city_id
   *
   * @return the value of bim_grab..cityarea_baidu.city_id
   *
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cityarea_baidu.city_id
   *
   * @param cityId the value for bim_grab..cityarea_baidu.city_id
   *
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cityarea_baidu.city_name
   *
   * @return the value of bim_grab..cityarea_baidu.city_name
   *
   * @mbggenerated
   */
  public String getCityName() {
    return cityName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cityarea_baidu.city_name
   *
   * @param cityName the value for bim_grab..cityarea_baidu.city_name
   *
   * @mbggenerated
   */
  public void setCityName(String cityName) {
    this.cityName = cityName == null ? null : cityName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..cityarea_baidu.name
   *
   * @return the value of bim_grab..cityarea_baidu.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..cityarea_baidu.name
   *
   * @param name the value for bim_grab..cityarea_baidu.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }
}
