package com.family.grabserver.entity.bim_grab;

public class MovieshowingWeixin {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.image
   *
   * @mbggenerated
   */
  private String image;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.rating
   *
   * @mbggenerated
   */
  private Float rating;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.directors
   *
   * @mbggenerated
   */
  private String directors;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.actors
   *
   * @mbggenerated
   */
  private String actors;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.type
   *
   * @mbggenerated
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.content
   *
   * @mbggenerated
   */
  private String content;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.runTime
   *
   * @mbggenerated
   */
  private String runtime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_grab..movieshowing_weixin.ver
   *
   * @mbggenerated
   */
  private String ver;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.id
   *
   * @return the value of bim_grab..movieshowing_weixin.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_grab..movieshowing_weixin.id
     *
     * @param id the value for bim_grab..movieshowing_weixin.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.name
   *
   * @return the value of bim_grab..movieshowing_weixin.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.name
   *
   * @param name the value for bim_grab..movieshowing_weixin.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.image
   *
   * @return the value of bim_grab..movieshowing_weixin.image
   *
   * @mbggenerated
   */
  public String getImage() {
    return image;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.image
   *
   * @param image the value for bim_grab..movieshowing_weixin.image
   *
   * @mbggenerated
   */
  public void setImage(String image) {
    this.image = image == null ? null : image.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.rating
   *
   * @return the value of bim_grab..movieshowing_weixin.rating
   *
   * @mbggenerated
   */
  public Float getRating() {
    return rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.rating
   *
   * @param rating the value for bim_grab..movieshowing_weixin.rating
   *
   * @mbggenerated
   */
  public void setRating(Float rating) {
    this.rating = rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.directors
   *
   * @return the value of bim_grab..movieshowing_weixin.directors
   *
   * @mbggenerated
   */
  public String getDirectors() {
    return directors;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.directors
   *
   * @param directors the value for bim_grab..movieshowing_weixin.directors
   *
   * @mbggenerated
   */
  public void setDirectors(String directors) {
    this.directors = directors == null ? null : directors.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.actors
   *
   * @return the value of bim_grab..movieshowing_weixin.actors
   *
   * @mbggenerated
   */
  public String getActors() {
    return actors;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.actors
   *
   * @param actors the value for bim_grab..movieshowing_weixin.actors
   *
   * @mbggenerated
   */
  public void setActors(String actors) {
    this.actors = actors == null ? null : actors.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.type
   *
   * @return the value of bim_grab..movieshowing_weixin.type
   *
   * @mbggenerated
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.type
   *
   * @param type the value for bim_grab..movieshowing_weixin.type
   *
   * @mbggenerated
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.content
   *
   * @return the value of bim_grab..movieshowing_weixin.content
   *
   * @mbggenerated
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.content
   *
   * @param content the value for bim_grab..movieshowing_weixin.content
   *
   * @mbggenerated
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.runTime
   *
   * @return the value of bim_grab..movieshowing_weixin.runTime
   *
   * @mbggenerated
   */
  public String getRuntime() {
    return runtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.runTime
   *
   * @param runtime the value for bim_grab..movieshowing_weixin.runTime
   *
   * @mbggenerated
   */
  public void setRuntime(String runtime) {
    this.runtime = runtime == null ? null : runtime.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_grab..movieshowing_weixin.ver
   *
   * @return the value of bim_grab..movieshowing_weixin.ver
   *
   * @mbggenerated
   */
  public String getVer() {
    return ver;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_grab..movieshowing_weixin.ver
   *
   * @param ver the value for bim_grab..movieshowing_weixin.ver
   *
   * @mbggenerated
   */
  public void setVer(String ver) {
    this.ver = ver == null ? null : ver.trim();
  }
}
