package com.family.grabserver.entity.bim_base;

public class CityArea {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city_area.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city_area.city_id
   *
   * @mbggenerated
   */
  private Integer cityId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city_area.area
   *
   * @mbggenerated
   */
  private String area;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city_area.id
   *
   * @return the value of bim_base..city_area.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city_area.id
   *
   * @param id the value for bim_base..city_area.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city_area.city_id
   *
   * @return the value of bim_base..city_area.city_id
   * @mbggenerated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city_area.city_id
   *
   * @param cityId the value for bim_base..city_area.city_id
   * @mbggenerated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city_area.area
   *
   * @return the value of bim_base..city_area.area
   * @mbggenerated
   */
  public String getArea() {
    return area;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city_area.area
   *
   * @param area the value for bim_base..city_area.area
   * @mbggenerated
   */
  public void setArea(String area) {
    this.area = area == null ? null : area.trim();
  }
}
