package com.family.grabserver.entity.bim_base;

public class City {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.first_letter
   *
   * @mbggenerated
   */
  private String firstLetter;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.pinyin
   *
   * @mbggenerated
   */
  private String pinyin;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.id_maoyan
   *
   * @mbggenerated
   */
  private Integer idMaoyan;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.id_mtime
   *
   * @mbggenerated
   */
  private Integer idMtime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..city.id_baidu
   *
   * @mbggenerated
   */
  private Integer idBaidu;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.id
   *
   * @return the value of bim_base..city.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.id
   *
   * @param id the value for bim_base..city.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.name
   *
   * @return the value of bim_base..city.name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.name
   *
   * @param name the value for bim_base..city.name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.first_letter
   *
   * @return the value of bim_base..city.first_letter
   * @mbggenerated
   */
  public String getFirstLetter() {
    return firstLetter;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.first_letter
   *
   * @param firstLetter the value for bim_base..city.first_letter
   * @mbggenerated
   */
  public void setFirstLetter(String firstLetter) {
    this.firstLetter = firstLetter == null ? null : firstLetter.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.pinyin
   *
   * @return the value of bim_base..city.pinyin
   * @mbggenerated
   */
  public String getPinyin() {
    return pinyin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.pinyin
   *
   * @param pinyin the value for bim_base..city.pinyin
   * @mbggenerated
   */
  public void setPinyin(String pinyin) {
    this.pinyin = pinyin == null ? null : pinyin.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.id_maoyan
   *
   * @return the value of bim_base..city.id_maoyan
   * @mbggenerated
   */
  public Integer getIdMaoyan() {
    return idMaoyan;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.id_maoyan
   *
   * @param idMaoyan the value for bim_base..city.id_maoyan
   * @mbggenerated
   */
  public void setIdMaoyan(Integer idMaoyan) {
    this.idMaoyan = idMaoyan;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.id_mtime
   *
   * @return the value of bim_base..city.id_mtime
   * @mbggenerated
   */
  public Integer getIdMtime() {
    return idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.id_mtime
   *
   * @param idMtime the value for bim_base..city.id_mtime
   * @mbggenerated
   */
  public void setIdMtime(Integer idMtime) {
    this.idMtime = idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..city.id_baidu
   *
   * @return the value of bim_base..city.id_baidu
   * @mbggenerated
   */
  public Integer getIdBaidu() {
    return idBaidu;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..city.id_baidu
   *
   * @param idBaidu the value for bim_base..city.id_baidu
   * @mbggenerated
   */
  public void setIdBaidu(Integer idBaidu) {
    this.idBaidu = idBaidu;
  }
}
