package com.family.grabserver.entity.bim_base;

public class Comment {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.movie_id
   *
   * @mbggenerated
   */
  private Integer movieId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.title
   *
   * @mbggenerated
   */
  private String title;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.nick_name
   *
   * @mbggenerated
   */
  private String nickName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.rating
   *
   * @mbggenerated
   */
  private Float rating;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.source_id
   *
   * @mbggenerated
   */
  private Integer sourceId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.id_mtime
   *
   * @mbggenerated
   */
  private Integer idMtime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..comment.content
   *
   * @mbggenerated
   */
  private String content;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.id
   *
   * @return the value of bim_base..comment.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_base..comment.id
     *
     * @param id the value for bim_base..comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.movie_id
   *
   * @return the value of bim_base..comment.movie_id
   *
   * @mbggenerated
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.movie_id
   *
   * @param movieId the value for bim_base..comment.movie_id
   *
   * @mbggenerated
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.title
   *
   * @return the value of bim_base..comment.title
   *
   * @mbggenerated
   */
  public String getTitle() {
    return title;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.title
   *
   * @param title the value for bim_base..comment.title
   *
   * @mbggenerated
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.nick_name
   *
   * @return the value of bim_base..comment.nick_name
   *
   * @mbggenerated
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.nick_name
   *
   * @param nickName the value for bim_base..comment.nick_name
   *
   * @mbggenerated
   */
  public void setNickName(String nickName) {
    this.nickName = nickName == null ? null : nickName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.rating
   *
   * @return the value of bim_base..comment.rating
   *
   * @mbggenerated
   */
  public Float getRating() {
    return rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.rating
   *
   * @param rating the value for bim_base..comment.rating
   *
   * @mbggenerated
   */
  public void setRating(Float rating) {
    this.rating = rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.source_id
   *
   * @return the value of bim_base..comment.source_id
   *
   * @mbggenerated
   */
  public Integer getSourceId() {
    return sourceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.source_id
   *
   * @param sourceId the value for bim_base..comment.source_id
   *
   * @mbggenerated
   */
  public void setSourceId(Integer sourceId) {
    this.sourceId = sourceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.id_mtime
   *
   * @return the value of bim_base..comment.id_mtime
   *
   * @mbggenerated
   */
  public Integer getIdMtime() {
    return idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.id_mtime
   *
   * @param idMtime the value for bim_base..comment.id_mtime
   *
   * @mbggenerated
   */
  public void setIdMtime(Integer idMtime) {
    this.idMtime = idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..comment.content
   *
   * @return the value of bim_base..comment.content
   *
   * @mbggenerated
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..comment.content
   *
   * @param content the value for bim_base..comment.content
   *
   * @mbggenerated
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }
}
