package com.family.grabserver.entity.bim_base;

public class Movieshowing {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.image
   *
   * @mbggenerated
   */
  private String image;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.rating
   *
   * @mbggenerated
   */
  private Double rating;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.is_imax
   *
   * @mbggenerated
   */
  private Boolean isImax;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.is_3d
   *
   * @mbggenerated
   */
  private Boolean is3d;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.directors
   *
   * @mbggenerated
   */
  private String directors;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.actors
   *
   * @mbggenerated
   */
  private String actors;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.type
   *
   * @mbggenerated
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.content
   *
   * @mbggenerated
   */
  private String content;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.runTime
   *
   * @mbggenerated
   */
  private String runtime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.id_maoyan
   *
   * @mbggenerated
   */
  private Integer idMaoyan;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.id_mtime
   *
   * @mbggenerated
   */
  private Integer idMtime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column bim_base..movieshowing.id_baidu
   *
   * @mbggenerated
   */
  private Integer idBaidu;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.id
   *
   * @return the value of bim_base..movieshowing.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim_base..movieshowing.id
     *
     * @param id the value for bim_base..movieshowing.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
      this.id = id;
    }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.name
   *
   * @return the value of bim_base..movieshowing.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.name
   *
   * @param name the value for bim_base..movieshowing.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.image
   *
   * @return the value of bim_base..movieshowing.image
   *
   * @mbggenerated
   */
  public String getImage() {
    return image;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.image
   *
   * @param image the value for bim_base..movieshowing.image
   *
   * @mbggenerated
   */
  public void setImage(String image) {
    this.image = image == null ? null : image.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.rating
   *
   * @return the value of bim_base..movieshowing.rating
   *
   * @mbggenerated
   */
  public Double getRating() {
    return rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.rating
   *
   * @param rating the value for bim_base..movieshowing.rating
   *
   * @mbggenerated
   */
  public void setRating(Double rating) {
    this.rating = rating;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.is_imax
   *
   * @return the value of bim_base..movieshowing.is_imax
   *
   * @mbggenerated
   */
  public Boolean getIsImax() {
    return isImax;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.is_imax
   *
   * @param isImax the value for bim_base..movieshowing.is_imax
   *
   * @mbggenerated
   */
  public void setIsImax(Boolean isImax) {
    this.isImax = isImax;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.is_3d
   *
   * @return the value of bim_base..movieshowing.is_3d
   *
   * @mbggenerated
   */
  public Boolean getIs3d() {
    return is3d;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.is_3d
   *
   * @param is3d the value for bim_base..movieshowing.is_3d
   *
   * @mbggenerated
   */
  public void setIs3d(Boolean is3d) {
    this.is3d = is3d;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.directors
   *
   * @return the value of bim_base..movieshowing.directors
   *
   * @mbggenerated
   */
  public String getDirectors() {
    return directors;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.directors
   *
   * @param directors the value for bim_base..movieshowing.directors
   *
   * @mbggenerated
   */
  public void setDirectors(String directors) {
    this.directors = directors == null ? null : directors.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.actors
   *
   * @return the value of bim_base..movieshowing.actors
   *
   * @mbggenerated
   */
  public String getActors() {
    return actors;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.actors
   *
   * @param actors the value for bim_base..movieshowing.actors
   *
   * @mbggenerated
   */
  public void setActors(String actors) {
    this.actors = actors == null ? null : actors.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.type
   *
   * @return the value of bim_base..movieshowing.type
   *
   * @mbggenerated
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.type
   *
   * @param type the value for bim_base..movieshowing.type
   *
   * @mbggenerated
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.content
   *
   * @return the value of bim_base..movieshowing.content
   *
   * @mbggenerated
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.content
   *
   * @param content the value for bim_base..movieshowing.content
   *
   * @mbggenerated
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.runTime
   *
   * @return the value of bim_base..movieshowing.runTime
   *
   * @mbggenerated
   */
  public String getRuntime() {
    return runtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.runTime
   *
   * @param runtime the value for bim_base..movieshowing.runTime
   *
   * @mbggenerated
   */
  public void setRuntime(String runtime) {
    this.runtime = runtime == null ? null : runtime.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.id_maoyan
   *
   * @return the value of bim_base..movieshowing.id_maoyan
   *
   * @mbggenerated
   */
  public Integer getIdMaoyan() {
    return idMaoyan;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.id_maoyan
   *
   * @param idMaoyan the value for bim_base..movieshowing.id_maoyan
   *
   * @mbggenerated
   */
  public void setIdMaoyan(Integer idMaoyan) {
    this.idMaoyan = idMaoyan;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.id_mtime
   *
   * @return the value of bim_base..movieshowing.id_mtime
   *
   * @mbggenerated
   */
  public Integer getIdMtime() {
    return idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.id_mtime
   *
   * @param idMtime the value for bim_base..movieshowing.id_mtime
   *
   * @mbggenerated
   */
  public void setIdMtime(Integer idMtime) {
    this.idMtime = idMtime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column bim_base..movieshowing.id_baidu
   *
   * @return the value of bim_base..movieshowing.id_baidu
   *
   * @mbggenerated
   */
  public Integer getIdBaidu() {
    return idBaidu;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column bim_base..movieshowing.id_baidu
   *
   * @param idBaidu the value for bim_base..movieshowing.id_baidu
   *
   * @mbggenerated
   */
  public void setIdBaidu(Integer idBaidu) {
    this.idBaidu = idBaidu;
  }
}
