package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CinemaMaoyan;

import java.util.List;

public interface CinemaMaoyanMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_maoyan
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_maoyan
   *
   * @mbggenerated
   */
  int insert(CinemaMaoyan record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_maoyan
   *
   * @mbggenerated
   */
  CinemaMaoyan selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_maoyan
   *
   * @mbggenerated
   */
  List<CinemaMaoyan> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_maoyan
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CinemaMaoyan record);

  List<CinemaMaoyan> selectByMaoyanCityId(Integer cityId);

}
