package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CinemamovieMtime;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CinemamovieMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinemamovie_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinemamovie_mtime
   *
   * @mbggenerated
   */
  int insert(CinemamovieMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinemamovie_mtime
   *
   * @mbggenerated
   */
  CinemamovieMtime selectByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinemamovie_mtime
   *
   * @mbggenerated
   */
  List<CinemamovieMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinemamovie_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CinemamovieMtime record);
}
