package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CinemaWeixin;

import java.util.List;

public interface CinemaWeixinMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_weixin
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_weixin
   *
   * @mbggenerated
   */
  int insert(CinemaWeixin record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_weixin
   *
   * @mbggenerated
   */
  CinemaWeixin selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_weixin
   *
   * @mbggenerated
   */
  List<CinemaWeixin> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_weixin
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CinemaWeixin record);
}
