package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CinemaMtime;

import java.util.List;

public interface CinemaMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_mtime
   *
   * @mbggenerated
   */
  int insert(CinemaMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_mtime
   *
   * @mbggenerated
   */
  CinemaMtime selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_mtime
   *
   * @mbggenerated
   */
  List<CinemaMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cinema_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CinemaMtime record);
}
