package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CityWithArea;

import java.util.List;

public interface CityWithAreaMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_with_area
   *
   * @mbggenerated
   */
  int insert(CityWithArea record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_with_area
   *
   * @mbggenerated
   */
  List<CityWithArea> selectAll();
}
