package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CityMaoyan;

import java.util.List;

public interface CityMaoyanMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_maoyan
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_maoyan
   *
   * @mbggenerated
   */
  int insert(CityMaoyan record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_maoyan
   *
   * @mbggenerated
   */
  CityMaoyan selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_maoyan
   *
   * @mbggenerated
   */
  List<CityMaoyan> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_maoyan
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CityMaoyan record);
}
