package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CityWeixin;

import java.util.List;

public interface CityWeixinMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_weixin
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_weixin
   *
   * @mbggenerated
   */
  int insert(CityWeixin record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_weixin
   *
   * @mbggenerated
   */
  CityWeixin selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_weixin
   *
   * @mbggenerated
   */
  List<CityWeixin> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_weixin
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CityWeixin record);
}
