package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CityTaobao;

import java.util.List;

public interface CityTaobaoMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_taobao
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_taobao
   *
   * @mbggenerated
   */
  int insert(CityTaobao record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_taobao
   *
   * @mbggenerated
   */
  CityTaobao selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_taobao
   *
   * @mbggenerated
   */
  List<CityTaobao> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..city_taobao
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CityTaobao record);
}
