package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CityareaMtime;

import java.util.List;

public interface CityareaMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cityarea_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cityarea_mtime
   *
   * @mbggenerated
   */
  int insert(CityareaMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cityarea_mtime
   *
   * @mbggenerated
   */
  CityareaMtime selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cityarea_mtime
   *
   * @mbggenerated
   */
  List<CityareaMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..cityarea_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CityareaMtime record);
}
