package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.CommentMtime;

import java.util.List;

public interface CommentMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..comment_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..comment_mtime
   *
   * @mbggenerated
   */
  int insert(CommentMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..comment_mtime
   *
   * @mbggenerated
   */
  CommentMtime selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..comment_mtime
   *
   * @mbggenerated
   */
  List<CommentMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..comment_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(CommentMtime record);
}
