package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.ImageMtime;

import java.util.List;

public interface ImageMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..image_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..image_mtime
   *
   * @mbggenerated
   */
  int insert(ImageMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..image_mtime
   *
   * @mbggenerated
   */
  ImageMtime selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..image_mtime
   *
   * @mbggenerated
   */
  List<ImageMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..image_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ImageMtime record);
}
