package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.MovieshowingWeixin;

import java.util.List;

public interface MovieshowingWeixinMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_weixin
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_weixin
   *
   * @mbggenerated
   */
  int insert(MovieshowingWeixin record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_weixin
   *
   * @mbggenerated
   */
  MovieshowingWeixin selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_weixin
   *
   * @mbggenerated
   */
  List<MovieshowingWeixin> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_weixin
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(MovieshowingWeixin record);
}
