package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.MovieshowingMtime;

import java.util.List;

public interface MovieshowingMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_mtime
   *
   * @mbggenerated
   */
  int insert(MovieshowingMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_mtime
   *
   * @mbggenerated
   */
  MovieshowingMtime selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_mtime
   *
   * @mbggenerated
   */
  List<MovieshowingMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(MovieshowingMtime record);
}
