package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.MovieshowingMaoyan;

import java.util.List;

public interface MovieshowingMaoyanMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_maoyan
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_maoyan
   *
   * @mbggenerated
   */
  int insert(MovieshowingMaoyan record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_maoyan
   *
   * @mbggenerated
   */
  MovieshowingMaoyan selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_maoyan
   *
   * @mbggenerated
   */
  List<MovieshowingMaoyan> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..movieshowing_maoyan
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(MovieshowingMaoyan record);
}
