package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.ScreeningWeixin;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScreeningWeixinMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_weixin
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_weixin
   *
   * @mbggenerated
   */
  int insert(ScreeningWeixin record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_weixin
   *
   * @mbggenerated
   */
  ScreeningWeixin selectByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_weixin
   *
   * @mbggenerated
   */
  List<ScreeningWeixin> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_weixin
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ScreeningWeixin record);
}
