package com.family.grabserver.mapper.bim_grab;

import com.family.grabserver.entity.bim_grab.ScreeningMtime;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScreeningMtimeMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_mtime
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_mtime
   *
   * @mbggenerated
   */
  int insert(ScreeningMtime record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_mtime
   *
   * @mbggenerated
   */
  ScreeningMtime selectByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_mtime
   *
   * @mbggenerated
   */
  List<ScreeningMtime> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table bim_grab..screening_mtime
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ScreeningMtime record);
}
