package com.family.webserver.mapper;

import com.family.webserver.entity.Screening;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScreeningMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table screening
   *
   * @mbggenerated Wed Feb 03 15:42:13 CST 2016
   */
  int deleteByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall, @Param("sourceId") Integer sourceId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table screening
   *
   * @mbggenerated Wed Feb 03 15:42:13 CST 2016
   */
  int insert(Screening record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table screening
   *
   * @mbggenerated Wed Feb 03 15:42:13 CST 2016
   */
  Screening selectByPrimaryKey(@Param("cinemaId") Integer cinemaId, @Param("movieId") Integer movieId, @Param("showDate") Date showDate, @Param("startTime") Date startTime, @Param("hall") String hall, @Param("sourceId") Integer sourceId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table screening
   *
   * @mbggenerated Wed Feb 03 15:42:13 CST 2016
   */
  List<Screening> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table screening
   *
   * @mbggenerated Wed Feb 03 15:42:13 CST 2016
   */
  int updateByPrimaryKey(Screening record);
}
